services:
    Customize\Service\PurchaseFlow\PurchaseFlow:
        decorates: Eccube\Service\PurchaseFlow\PurchaseFlow
    
    Customize\Service\CartService:
        decorates: Eccube\Service\CartService
    
    Customize\Service\CsvExportService:
        decorates: Eccube\Service\CsvExportService
    
    Customize\Service\MailService:
        decorates: Eccube\Service\MailService
    
    Customize\Service\OrderHelper:
        decorates: Eccube\Service\OrderHelper