<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\restaurant_food\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\restaurant_food\Entity\RestaurantTag;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * RestaurantTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantTagRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, RestaurantTag::class);
    }
}
